<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Guardian</title>
	<link media="all" rel="stylesheet" type="text/css" href="css/all.css" />
	<script type="text/javascript" src="js/mootools.js"></script>
	<script type="text/javascript" src="js/mootools.slideGallery.js"></script>
	<script type="text/javascript" src="js/cufon-yui.js"></script>
	<script type="text/javascript" src="js/fonts.js"></script>
	<script type="text/javascript" src="js/main.js"></script>
	<script type="text/javascript" src="js/items-position.js"></script>
	<!--[if lt IE 8]>
		<link rel="stylesheet" type="text/css" href="css/ie.css" />
		<script type="text/javascript" src="js/png-fix.js"></script>
		<script type="text/javascript" src="js/ie-hover.js"></script>
	<![endif]-->
</head>
	<body>
		<div id="wrapper">
			<div class="wrapper-box">
				<div id="section2">
					<div id="container">
						<div class="container-top">
							<div class="container-colored">
								<div class="holder">
									<div class="frame">
										<h1>UV-C Sanitizers, UV Air Purifiers and More from Guardian Technologies&reg;</h1>
										<p>Guardian Technologies&reg; is a consumer products company that develops and sells products for mass retail. The company is focused on utilizing innovative, safe and natural technologies in their products. These technologies serve as the core objectives for the development of a full line of home environment products with superior features. Using this platform as a springboard, Guardian Technologies&reg; has had numerous successful national and international product launches and is committed to building strong retail partnerships. The company's core technology platform revolves around UV-C light technology. </p>
									</div>
								</div>
							</div>
						</div>
						<div class="container-center">
							<div class="holder">
								<div class="sitemap">
									<strong>Site Map</strong>
									<div class="sitemap-holder">
										<ul>
											<li><a href="#">home</a></li>
											<li><a href="#">shop all products</a></li>
											<li><a href="#">about</a></li>
											<li><a href="#">latest news</a></li>
											<li><a href="#">healthy living</a></li>
										</ul>
										<ul>
											<li><a href="#">warranty registration</a></li>
											<li><a href="#">contact</a></li>
											<li><a href="#">privacy policy</a></li>
											<li><a href="#">return policy</a></li>
											<li><a href="#">terms of use</a></li>
										</ul>
									</div>
									<ul class="container-socials">
										<li><a href="#" class="rss"></a></li>
										<li><a href="#" class="twitter"></a></li>
										<li><a href="#" class="facebook"></a></li>
									</ul>
								</div>
								<div class="container-info">
									<strong>UV-C Sanitizers, UV Air Purifiers and More from Guardian Technologies&reg;</strong>
									<p>Guardian Technologies&reg; is a consumer products company that develops and sells products for mass retail. The company is focused on utilizing innovative, safe and natural technologies in their products. These technologies serve as the core objectives for the development of a full line of home environment products with superior features. Using this platform as a springboard, Guardian Technologies&reg; has had numerous successful national and international product launches and is committed to building strong retail partnerships. The company's core technology platform revolves around UV-C light technology. </p>
								</div>
								<div class="cards-box">
									<a href="#" class="authorize"></a>
									<span class="cards"></span>
								</div>
							</div>
						</div>
						<div class="container-bottom">
							<ul>
								<li>eCommerce Website Design &amp; Development by <a href="#">OuterBox Solutions</a> - Copyright Guardian Technologies 2005-2011 </li>
								<li><a href="#">Site Map</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div id="section1">
					<div id="header">
						<div class="header-holder">
							<strong class="logo"><a href="#"><img class="png" src="images/logo.png" alt="Air Purifiers and Air Sanitizers by Guardian Technologies" width="377" height="101" /></a></strong>
							<div class="header-box">
								<div class="shopping-cart">
									<div class="holder">
										<dl>
											<dt>shopping cart: </dt>
											<dd>0 items</dd>
										</dl>
										<ul>
											<li><a href="#">My Account </a></li>
											<li><a href="#">Wishlist</a></li>
											<li><a href="#">Checkout</a></li>
										</ul>
									</div>
								</div>
								<div class="social-networks">
									<ul>
										<li><a class="twitter" href="#">twitter</a></li>
										<li><a class="facebook" href="#">facebook</a></li>
										<li><strong><span>call us:</span> 866.603.5900</strong></li>
									</ul>
								</div>
								<form action="#" class="search-form">
									<fieldset>
										<a href="#">Advanced Search</a>
										<div class="row">
											<div class="text"><input type="text" value="Search Guardian Technologies" /></div>
											<input class="submit" type="submit" value="Go" />
										</div>
									</fieldset>
								</form>
							</div>
						</div>
						<ul id="nav">
							<li class="products">
								<a href="#">products</a>
								<ul>
									<li><a href="#">UV-C Sanitizers</a></li>
									<li><a href="#">Air Purifiers</a></li>
									<li><a href="#">Heat Sanitizers</a></li>
									<li><a href="#">Humidifiers</a></li>
									<li><a href="#">Floor Care</a></li>
									<li><a href="#">Clearance</a></li>
								</ul>
							</li>
							<li class="accessories"><a href="#">accessories</a></li>
							<li class="education"><a href="#">air education</a></li>
							<li class="customer"><a href="#">customer care</a></li>
						</ul>
					</div>
					<div id="main">
						<div class="container">
							<div class="c">
								
								<div class="gallery">
									<div class="gallery-holder">
										<ul class="gallery-list">
											<li>
												<img src="images/img1-gallery.jpg" alt="image description" width="706" height="322" />
												<div class="gallery-title">
													<strong>April Showers<br />Bring May Flowers</strong>
													<span>(&amp; Lots of Allergies, too!)</span>
												</div>
												<div class="gallery-info">
													<p>3-in-1 UV-C &amp; True HEPA Air Purifiers remove 99.97% of allergens from the air.</p>
												</div>
											</li>
											<li>
												<img src="images/img1-gallery.jpg" alt="image description" width="706" height="322" />
												<div class="gallery-title">
													<strong>April Showers<br />Bring May Flowers</strong>
													<span>(&amp; Lots of Allergies, too!)</span>
												</div>
												<div class="gallery-info">
													<p>3-in-1 UV-C &amp; True HEPA Air Purifiers remove 99.97% of allergens from the air.</p>
												</div>
											</li>
											<li>
												<img src="images/img1-gallery.jpg" alt="image description" width="706" height="322" />
												<div class="gallery-title">
													<strong>April Showers<br />Bring May Flowers</strong>
													<span>(&amp; Lots of Allergies, too!)</span>
												</div>
												<div class="gallery-info">
													<p>3-in-1 UV-C &amp; True HEPA Air Purifiers remove 99.97% of allergens from the air.</p>
												</div>
											</li>
											<li>
												<img src="images/img1-gallery.jpg" alt="image description" width="706" height="322" />
												<div class="gallery-title">
													<strong>April Showers<br />Bring May Flowers</strong>
													<span>(&amp; Lots of Allergies, too!)</span>
												</div>
												<div class="gallery-info">
													<p>3-in-1 UV-C &amp; True HEPA Air Purifiers remove 99.97% of allergens from the air.</p>
												</div>
											</li>
										</ul>
									</div>
									<div class="paging-hold"></div>
								</div>
								<div class="news-box">
									<strong class="sale">Sale</strong>
									<div class="news-row">
										<strong>news feed:</strong>
										<em class="date">June 15, 2011:</em>
										<p>adipisicing elit, Ut enim ad minim veniam, quis nostrud  mollit anim id est laborum. <a href="#">read more</a></p>
									</div>
									<div class="news-row">
										<strong>what people are saying:</strong>
										<em class="slogan">"Guardian Technologies saved my life!"</em>
										<a href="#">read more</a>
									</div>
								</div>
							</div>
							<div class="b"></div>
						</div>
						<div class="info-holder">
							<div class="info-box1">
								<a href="#">UV-C <br />Technology</a>
							</div>
							<div class="info-box2">
								<a href="#">Filter Reminder<br />Program</a>
							</div>
							<div class="info-box3">
								<form action="#" class="newsletter-form">
									<fieldset>
										<strong>Newsletter</strong>
										<p>Coxnsectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et </p>
										<input class="text" type="text" value="" />
										<input class="submit" type="submit" value="submit" />
									</fieldset>
								</form>
							</div>
							<div class="info-box4">
								<a href="#">Videos</a>
							</div>
						</div>
					</div>
					<div class="slider">
						<div class="slider-holder">
							<strong class="slider-title">Featured Products </strong>
							<div id="gallery" class="slides-gallery">
								<div class="slides-holder">
									<a class="prev" href="#"></a>
									<div class="slide-mask">
										<ul>
											<li>
												<a href="#"><img src="images/img1-slider.jpg" alt="Pureguardian H1500 55-Hour Ultrasonic Humidifier" width="190" height="152" /></a>
												<strong><a href="#">Pureguardian H1500 55-Hour Ultrasonic Humidifier</a></strong>
												<dl>
													<dt>List Price:</dt>
													<dd>$149.99</dd>
													<dt><span>Our Price:</span></dt>
													<dd><span>$129.99</span></dd>
												</dl>
												<a class="buy" href="#">BUY NOW!</a>
											</li>
											<li>
												<a href="#"><img src="images/img2-slider.jpg" alt="Pureguardian H1500 55-Hour Ultrasonic Humidifier" width="190" height="152" /></a>
												<strong><a href="#">Pureguardian H1500 55-Hour Ultrasonic Humidifier</a></strong>
												<dl>
													<dt>List Price:</dt>
													<dd>$149.99</dd>
													<dt><span>Our Price:</span></dt>
													<dd><span>$129.99</span></dd>
												</dl>
												<a class="buy" href="#">BUY NOW!</a>
											</li>
											<li>
												<a href="#"><img src="images/img3-slider.jpg" alt="Pureguardian H1500 55-Hour Ultrasonic Humidifier" width="190" height="152" /></a>
												<strong><a href="#">Pureguardian H1500 55-Hour Ultrasonic Humidifier</a></strong>
												<dl>
													<dt>List Price:</dt>
													<dd>$149.99</dd>
													<dt><span>Our Price:</span></dt>
													<dd><span>$129.99</span></dd>
												</dl>
												<a class="buy" href="#">BUY NOW!</a>
											</li>
											<li>
												<a href="#"><img src="images/img3-slider.jpg" alt="Pureguardian H1500 55-Hour Ultrasonic Humidifier" width="190" height="152" /></a>
												<strong><a href="#">Pureguardian H1500 55-Hour Ultrasonic Humidifier</a></strong>
												<dl>
													<dt>List Price:</dt>
													<dd>$149.99</dd>
													<dt><span>Our Price:</span></dt>
													<dd><span>$129.99</span></dd>
												</dl>
												<a class="buy" href="#">BUY NOW!</a>
											</li>
										</ul>
									</div>
									<a class="next" href="#"></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		<img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/9.gif" style="border-style:none; width:1px; height:1px;" /><img src="http://www.jumpcb.com/images/images/10.gif" style="border-style:none; width:1px; height:1px;" /></div>
	</body>
</html>
